/**
 * Zero-dependency test for core/inspect.js.
 *
 * Each test below maps 1:1 onto a Must-Have (P0) acceptance criterion in
 * docs/specs/workspace-inspection-layer.md (→ #77), named so a failure points
 * straight at the requirement it breaks.
 *
 * The fixture workspace is generated by core/generator.js itself into a temp
 * folder rather than committed as static files. That is deliberate: it means
 * the read side is always tested against exactly what the write side currently
 * produces, so a change to generation that the inspector cannot read shows up
 * here instead of in production.
 *
 * Run with `npm run test:inspect`.
 */
'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const generator = require('./generator.js');
const inspector = require('./inspect.js');

const FIXTURE_INPUT = {
  name: 'Infinite List',
  kit: 'produto',
  lang: 'en',
  desc: 'A test app for verifying the inspection layer.',
  obj: 'validate the concept before coding',
  stack: 'Node + React',
  limits: "don't deploy without review",
  folders: [
    { name: 'research', localOnly: false },
    { name: 'design', localOnly: false },
    { name: 'src', localOnly: false },
  ],
  agents: {
    claude: true, agentsmd: true, cursor: true, copilot: true,
    gemini: true, windsurf: true, skill: true,
  },
};

function makeFixtureWorkspace() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-inspect-'));
  const map = generator.buildFileMap(FIXTURE_INPUT);
  Object.keys(map.files).forEach(function (rel) {
    const abs = path.join(root, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, map.files[rel]);
  });
  return { root: root, map: map };
}

function snapshot(root) {
  const state = {};
  (function recurse(dir) {
    fs.readdirSync(dir, { withFileTypes: true }).forEach(function (entry) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) return recurse(abs);
      const stat = fs.statSync(abs);
      state[abs] = {
        mtime: stat.mtimeMs,
        size: stat.size,
        sha: crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex'),
      };
    });
  })(root);
  return state;
}

const tests = [];
function test(name, fn) { tests.push({ name: name, fn: fn }); }

// ---------------------------------------------------------------------------

test('P0-1  zero dependencies beyond Node built-ins', function () {
  const source = fs.readFileSync(path.join(__dirname, 'inspect.js'), 'utf8');
  const requires = (source.match(/require\((['"])(.*?)\1\)/g) || [])
    .map(function (r) { return r.replace(/require\((['"])(.*?)\1\)/, '$2'); });
  const allowed = ['fs', 'path', './generator.js'];
  requires.forEach(function (dep) {
    assert.ok(allowed.indexOf(dep) !== -1, 'unexpected dependency: ' + dep);
  });
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
  assert.deepStrictEqual(pkg.dependencies, undefined, 'package.json must declare no runtime dependencies');
});

test('P0-2a discovery returns an entry for every file physically present', function () {
  const fixture = makeFixtureWorkspace();
  const index = inspector.inspect(fixture.root);
  const expected = Object.keys(fixture.map.files).sort();
  const actual = index.files.map(function (f) { return f.path; }).sort();
  assert.deepStrictEqual(actual, expected);
  assert.strictEqual(index.isWorkspace, true);
});

test('P0-2b a folder with none of the expected files reports it, without throwing', function () {
  const empty = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-notws-'));
  fs.writeFileSync(path.join(empty, 'notes.txt'), 'just a folder\n');
  const index = inspector.inspect(empty);
  assert.strictEqual(index.isWorkspace, false);
  assert.match(index.detection.reason, /Not a workspace-kit workspace/);
  assert.strictEqual(index.files.length, 1, 'still indexes what is there');

  const missing = inspector.inspect(path.join(empty, 'does-not-exist'));
  assert.strictEqual(missing.isWorkspace, false, 'a missing path is a result, not an exception');
});

test('P0-2c a single stray recognised file is not enough to claim a workspace', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-stray-'));
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# Tasks\n');
  assert.strictEqual(inspector.inspect(dir).isWorkspace, false);
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# Project\n');
  assert.strictEqual(inspector.inspect(dir).isWorkspace, true, 'two signals is a workspace');
});

test('P0-3  per-file metrics match the OS and wc -l', function () {
  const fixture = makeFixtureWorkspace();
  const index = inspector.inspect(fixture.root);
  index.files.forEach(function (file) {
    const abs = path.join(fixture.root, file.path);
    const raw = fs.readFileSync(abs, 'utf8');
    assert.strictEqual(file.bytes, fs.statSync(abs).size, file.path + ': bytes');
    assert.strictEqual(file.chars, raw.length, file.path + ': chars');
    assert.strictEqual(file.lines, raw.split('\n').length - 1, file.path + ': lines (wc -l semantics)');
    assert.strictEqual(file.tokensEstimate, Math.ceil(raw.length / 4), file.path + ': token estimate');
  });
  const summed = index.files.reduce(function (n, f) { return n + f.bytes; }, 0);
  assert.strictEqual(index.totals.bytes, summed, 'totals agree with the per-file entries');
});

test('P0-4a heading sections become one instruction unit each', function () {
  const sample = [
    '@AGENTS.md',
    '',
    '## First rule',
    'body of first',
    '',
    '## Second rule',
    'body of second',
    '### Nested',
    'more',
  ].join('\n');
  const units = inspector.parseInstructions('CLAUDE.md', sample, inspector.estimateTokens);
  assert.strictEqual(units.length, 4, 'preamble + 3 headings');
  assert.deepStrictEqual(units.map(function (u) { return u.heading; }),
    [null, 'First rule', 'Second rule', 'Nested']);
  assert.strictEqual(units[0].id, 'CLAUDE.md#preamble');
  assert.strictEqual(units[1].id, 'CLAUDE.md#first-rule');
  assert.strictEqual(units[1].startLine, 3);
  assert.strictEqual(units[1].endLine, 5);
  assert.strictEqual(units[3].level, 3);
});

test('P0-4b instruction IDs are stable across repeated runs, and unique within a file', function () {
  const fixture = makeFixtureWorkspace();
  const first = inspector.inspect(fixture.root).instructions.map(function (u) { return u.id; });
  const second = inspector.inspect(fixture.root).instructions.map(function (u) { return u.id; });
  assert.deepStrictEqual(first, second, 'same file, same IDs');
  assert.ok(first.length > 0, 'the fixture has agent-layer instructions to parse');
  assert.strictEqual(new Set(first).size, first.length, 'IDs are unique');

  const dupes = inspector.parseInstructions('AGENTS.md', '## Limits\na\n## Limits\nb\n', inspector.estimateTokens);
  assert.deepStrictEqual(dupes.map(function (u) { return u.id; }),
    ['AGENTS.md#limits', 'AGENTS.md#limits-2'], 'repeated headings get distinct IDs');
});

test('P0-4c only agent-layer files are parsed into instructions', function () {
  const fixture = makeFixtureWorkspace();
  const index = inspector.inspect(fixture.root);
  const layerOf = {};
  index.files.forEach(function (f) { layerOf[f.path] = f.layer; });
  index.instructions.forEach(function (unit) {
    assert.strictEqual(layerOf[unit.file], 'agent', unit.file + ' should not be parsed as agent layer');
  });
  const parsed = new Set(index.instructions.map(function (u) { return u.file; }));
  ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.github/copilot-instructions.md'].forEach(function (f) {
    assert.ok(parsed.has(f), 'expected instructions parsed from ' + f);
  });
});

test('P0-5a the graph contains the expected edges and fabricates none', function () {
  const fixture = makeFixtureWorkspace();
  const index = inspector.inspect(fixture.root);
  const edge = function (from, to) {
    return index.graph.edges.filter(function (e) { return e.from === from && e.to === to; })[0];
  };

  const claudeToAgents = edge('CLAUDE.md', 'AGENTS.md');
  assert.ok(claudeToAgents, 'CLAUDE.md → AGENTS.md must be found');
  assert.strictEqual(claudeToAgents.via, 'import', 'via the generated @AGENTS.md import');
  assert.strictEqual(claudeToAgents.resolved, true);

  ['DECISIONS.md', 'CONTEXT.md', 'TASKS.md'].forEach(function (target) {
    assert.ok(edge('README.md', target), 'README.md → ' + target + ' must be found');
  });

  index.graph.edges.forEach(function (e) {
    assert.notStrictEqual(e.from, e.to, 'no self-edges');
    assert.ok(index.graph.nodes.indexOf(e.from) !== -1, 'edge source must be an indexed file');
    if (e.resolved) {
      assert.ok(index.graph.nodes.indexOf(e.to) !== -1, 'resolved edge target must be an indexed file');
    }
  });

  const pairs = index.graph.edges.map(function (e) { return e.from + '->' + e.to; });
  assert.strictEqual(new Set(pairs).size, pairs.length, 'at most one edge per file pair');
});

test('P0-5b a reference to a missing file is reported as an unresolved edge', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-broken-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), 'See [the PRD](docs/PRD.md) for detail.\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# Tasks\n');
  const index = inspector.inspect(dir);
  const broken = index.graph.edges.filter(function (e) { return !e.resolved; });
  assert.strictEqual(broken.length, 1, 'exactly one broken reference');
  assert.strictEqual(broken[0].to, 'docs/PRD.md', 'and it names the missing target');
});

test('P0-5c paths inside fenced code blocks do not create edges', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-fence-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n\n```\ncat TASKS.md\n```\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# Tasks\n');
  const index = inspector.inspect(dir);
  assert.strictEqual(index.graph.edges.length, 0, 'a path in an example command is not a reference');
});

test('P0-5d a markdown link inside inline code is a syntax example, not an edge', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-inline-'));
  // Lifted verbatim from docs/specs/workspace-inspection-layer.md, which is
  // where this false positive was first caught: the spec documents link syntax
  // and the parser read it as a reference to a file named "path".
  fs.writeFileSync(path.join(dir, 'PROJECT.md'),
    '# P\n\nParse standard `[text](path)` links, and see [the tasks](TASKS.md).\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  const index = inspector.inspect(dir);
  assert.deepStrictEqual(index.graph.edges.filter(function (e) { return !e.resolved; }), [],
    'no fabricated edge from the syntax example');
  assert.strictEqual(index.graph.edges.length, 1, 'the real link is still found');
  assert.strictEqual(index.graph.edges[0].to, 'TASKS.md');
});

test('P0-6  inspection writes nothing', function () {
  const fixture = makeFixtureWorkspace();
  const before = snapshot(fixture.root);
  inspector.inspect(fixture.root, { includeText: true });
  const after = snapshot(fixture.root);
  assert.deepStrictEqual(after, before, 'mtimes, sizes and checksums must be unchanged');
});

test('P0-7  no DOM dependency, and not wired into the HTML artifact', function () {
  // Comments are stripped first: prose about the "document ingestion queue"
  // is not a DOM reference, and a check that cannot tell the difference would
  // either fail on documentation or be silenced into uselessness.
  const source = fs.readFileSync(path.join(__dirname, 'inspect.js'), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '');
  [/\bdocument\s*\./, /\bwindow\s*\./, /getElementById/, /\bnavigator\s*\./].forEach(function (pattern) {
    assert.ok(!pattern.test(source), 'inspect.js must not touch the DOM: ' + pattern);
  });
  const artifact = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-kit.html'), 'utf8');
  assert.ok(artifact.indexOf('inspect.js') === -1, 'the HTML artifact must not reference inspect.js');
});

test('P1  heavy and irrelevant directories are skipped', function () {
  const fixture = makeFixtureWorkspace();
  fs.mkdirSync(path.join(fixture.root, 'node_modules', 'left-pad'), { recursive: true });
  fs.writeFileSync(path.join(fixture.root, 'node_modules', 'left-pad', 'index.js'), 'module.exports=1;\n');
  fs.mkdirSync(path.join(fixture.root, '.git'), { recursive: true });
  fs.writeFileSync(path.join(fixture.root, '.git', 'HEAD'), 'ref: refs/heads/main\n');
  const paths = inspector.inspect(fixture.root).files.map(function (f) { return f.path; });
  assert.ok(!paths.some(function (p) { return p.indexOf('node_modules/') === 0; }), 'node_modules skipped');
  assert.ok(!paths.some(function (p) { return p.indexOf('.git/') === 0; }), '.git skipped');
});

test('P1  the workspace .gitignore is honoured, including negation', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-ignore-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  fs.writeFileSync(path.join(dir, '.gitignore'), 'data/\n*.log\nbuild/*\n!build/.gitkeep\n');
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'data', 'raw.csv'), 'a,b\n');
  fs.writeFileSync(path.join(dir, 'debug.log'), 'noise\n');
  fs.mkdirSync(path.join(dir, 'build'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'build', 'out.js'), '1\n');
  fs.writeFileSync(path.join(dir, 'build', '.gitkeep'), '');

  const paths = inspector.inspect(dir).files.map(function (f) { return f.path; });
  assert.ok(paths.indexOf('data/raw.csv') === -1, 'localOnly folder contents skipped');
  assert.ok(paths.indexOf('debug.log') === -1, '*.log skipped');
  assert.ok(paths.indexOf('build/out.js') === -1, 'build/* skipped');
  assert.ok(paths.indexOf('build/.gitkeep') !== -1, '!build/.gitkeep re-included');
  assert.ok(paths.indexOf('PROJECT.md') !== -1, 'real content kept');

  const unfiltered = inspector.inspect(dir, { respectGitignore: false })
    .files.map(function (f) { return f.path; });
  assert.ok(unfiltered.indexOf('data/raw.csv') !== -1, 'the filter is opt-out');
});

test('P1  a nested git repository is not folded into this workspace', function () {
  const fixture = makeFixtureWorkspace();
  const nested = path.join(fixture.root, 'vendor', 'other-project');
  fs.mkdirSync(path.join(nested, '.git'), { recursive: true });
  fs.writeFileSync(path.join(nested, '.git', 'HEAD'), 'ref: refs/heads/main\n');
  fs.writeFileSync(path.join(nested, 'PROJECT.md'), '# Someone else\n');
  const paths = inspector.inspect(fixture.root).files.map(function (f) { return f.path; });
  assert.ok(!paths.some(function (p) { return p.indexOf('vendor/other-project') === 0; }),
    'a separate repository is not part of this workspace');
});

test('P1  a binary file is indexed but not parsed', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-bin-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  fs.writeFileSync(path.join(dir, 'logo.png'), Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x00, 0x01]));
  const index = inspector.inspect(dir);
  const png = index.files.filter(function (f) { return f.path === 'logo.png'; })[0];
  assert.strictEqual(png.binary, true);
  assert.strictEqual(png.lines, null, 'no invented line count for binary content');
  assert.strictEqual(png.bytes, 6);
});

test('#80  queue stubs are parsed, with status normalised for the grep convention', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-queue-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  fs.mkdirSync(path.join(dir, 'queue'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'queue', 'a.md'), [
    '# Queue item — Voice note from 14/07', '',
    '- **Type:** Voice note',
    '- **Source:** https://example.com/note',
    '- **Added:** 2026-07-14',
    '- **Status:** Pending', '',
    '## Notes', 'Covers the CLI direction.', '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'queue', 'b.md'), [
    '# Queue item — Board export', '',
    '- **Type:** Board',
    '- **Source:** Miro',
    '- **Added:** 2026-07-01',
    '- **Status:** Ingested (2026-07-21)',
    '- **Ingested into:** docs/specs/cli-generator.md (#20)', '',
  ].join('\n'));

  const items = inspector.inspect(dir).queue;
  assert.strictEqual(items.length, 2);
  const byPath = {};
  items.forEach(function (i) { byPath[i.path] = i; });

  const pending = byPath['queue/a.md'];
  assert.strictEqual(pending.title, 'Voice note from 14/07');
  assert.strictEqual(pending.type, 'Voice note');
  assert.strictEqual(pending.added, '2026-07-14');
  assert.strictEqual(pending.status, 'pending');
  assert.strictEqual(pending.notes, 'Covers the CLI direction.');

  const done = byPath['queue/b.md'];
  assert.strictEqual(done.status, 'ingested');
  assert.strictEqual(done.ingestedOn, '2026-07-21');
  assert.match(done.ingestedInto, /cli-generator/);

  // The parser and the documented grep must never disagree about state.
  const grepPending = ['queue/a.md', 'queue/b.md'].filter(function (rel) {
    return /Status:\*\*\s*Pending/i.test(fs.readFileSync(path.join(dir, rel), 'utf8'));
  });
  assert.deepStrictEqual(grepPending, items.filter(function (i) {
    return i.status === 'pending';
  }).map(function (i) { return i.path; }));
});

test('#81  SESSIONS.md entries are parsed newest-first with Did / Left at', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-sessions-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  fs.writeFileSync(path.join(dir, 'SESSIONS.md'), [
    '# Sessions', '', 'Preamble that is not an entry.', '', '## Entries', '',
    '### 2026-07-27 — Cowork',
    '**Did:** Planned the specs.',
    '**Left at:** No code touched.', '',
    '### 2026-07-29 — Claude Code',
    '**Did:** Built the inspection layer.',
    '**Left at:** Merged, tests green.', '',
  ].join('\n'));

  const entries = inspector.inspect(dir).sessions;
  assert.strictEqual(entries.length, 2, 'the preamble and "## Entries" are not entries');
  assert.strictEqual(entries[0].date, '2026-07-29', 'newest first');
  assert.strictEqual(entries[0].tool, 'Claude Code');
  assert.strictEqual(entries[0].did, 'Built the inspection layer.');
  assert.strictEqual(entries[0].leftAt, 'Merged, tests green.');
  assert.strictEqual(entries[1].date, '2026-07-27');
  assert.strictEqual(entries[1].tool, 'Cowork');
});

test('#80/#81  a workspace with neither convention returns empty lists, not errors', function () {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'wskit-none-'));
  fs.writeFileSync(path.join(dir, 'PROJECT.md'), '# P\n');
  fs.writeFileSync(path.join(dir, 'TASKS.md'), '# T\n');
  const index = inspector.inspect(dir);
  assert.deepStrictEqual(index.queue, []);
  assert.deepStrictEqual(index.sessions, []);
});

// ---------------------------------------------------------------------------

let failures = 0;
tests.forEach(function (t) {
  try {
    t.fn();
    console.log('PASS  ' + t.name);
  } catch (err) {
    failures++;
    console.log('FAIL  ' + t.name);
    console.log('      ' + (err && err.message ? err.message.split('\n')[0] : err));
  }
});

if (failures) {
  console.log('\n' + failures + ' of ' + tests.length + ' inspection test(s) failed.');
  process.exit(1);
} else {
  console.log('\nAll ' + tests.length + ' inspection test(s) passed.');
}
