/**
 * workspace//kit — shared workspace inspection layer.
 *
 * The read-side counterpart to core/generator.js: generator.js turns a project
 * description into a set of files, this turns an existing folder back into an
 * addressable index of what is actually there. See
 * docs/specs/workspace-inspection-layer.md (→ #77).
 *
 * Consumers (workspace health check #78, git integration layer #79, document
 * ingestion queue #80, cross-tool session log #81, the Local Web App dashboard
 * #169, and the still-unspecced Markdown Orchestrator) all build on this one
 * index instead of each growing their own folder walker and markdown parser.
 * That duplication is the whole reason this module exists, so anything that
 * looks like domain judgement -- thresholds, verdicts, suggestions, git state,
 * rendering -- deliberately does NOT live here. This module reports; the
 * consumers decide.
 *
 * Node-only (`module.exports`), unlike generator.js's UMD-lite wrapper: reading
 * an arbitrary folder needs `fs`, so there is no browser surface to serve. See
 * the spec's Open Questions -- the reasonable default was Node-only until a
 * concrete in-browser need appears.
 *
 * Zero runtime dependencies beyond Node built-ins, no build step, matching
 * core/generator.js's conventions. To test: `npm run test:inspect`.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const generator = require('./generator.js');

/** Human-layer files, as generated by core/generator.js. */
const HUMAN_FILES = ['PROJECT.md', 'DECISIONS.md', 'CONTEXT.md', 'TASKS.md', 'README.md'];

/**
 * The four that actually signal "workspace//kit workspace". README.md is
 * excluded on purpose: almost every repository has one, so counting it would
 * make the detection below fire on folders that have nothing to do with us.
 */
const SIGNAL_FILES = ['PROJECT.md', 'DECISIONS.md', 'CONTEXT.md', 'TASKS.md'];

/** Agent-layer files at fixed paths. */
const AGENT_FILES = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.github/copilot-instructions.md'];

/**
 * Agent-layer files whose names depend on the project slug, matched by the
 * directory that contains them rather than by an exact filename.
 */
const AGENT_DIRS = ['.cursor/rules', '.windsurf/rules', '.claude/skills'];

/** Skipped during discovery: heavy, irrelevant, or not ours to read. */
const DEFAULT_IGNORES = ['.git', 'node_modules', '.DS_Store'];

const LAYER = {
  HUMAN: 'human',
  AGENT: 'agent',
  ANCHOR: 'anchor',
  OTHER: 'other',
};

/**
 * Every per-kit anchor file (docs/PRD.md, docs/GDD.md, …), read off
 * generator.js's own KIT_CONFIG rather than duplicated here — so adding a kit
 * on the write side teaches the read side about its anchor file for free.
 */
function anchorFilePaths() {
  const paths = new Set();
  Object.keys(generator.KIT_CONFIG || {}).forEach(function (kit) {
    const extra = generator.KIT_CONFIG[kit].extraFile;
    if (!extra || !extra.path) return;
    Object.keys(extra.path).forEach(function (lang) {
      paths.add(toPosix(extra.path[lang]));
    });
  });
  return paths;
}

function toPosix(p) {
  return p.split(path.sep).join('/');
}

/**
 * Token estimate: characters ÷ 4, the common rough approximation. It is an
 * estimate and callers must present it as one (see #169's P0 requirement that
 * no screen shows a token figure as exact). The method is deliberately
 * swappable via `options.estimateTokens` -- picking a real tokenizer would mean
 * taking on a dependency, which this module's zero-dependency convention rules
 * out, and the choice is still an open question in the spec.
 */
function estimateTokens(text) {
  return Math.ceil(text.length / 4);
}

/** Newline count, matching `wc -l` (a file with no trailing newline reports one fewer). */
function countLines(text) {
  let lines = 0;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === '\n') lines++;
  }
  return lines;
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[`*_~[\]()]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'section';
}

function classify(relPath, anchors) {
  if (HUMAN_FILES.indexOf(relPath) !== -1) return LAYER.HUMAN;
  if (AGENT_FILES.indexOf(relPath) !== -1) return LAYER.AGENT;
  for (let i = 0; i < AGENT_DIRS.length; i++) {
    if (relPath.indexOf(AGENT_DIRS[i] + '/') === 0) return LAYER.AGENT;
  }
  if (anchors.has(relPath)) return LAYER.ANCHOR;
  return LAYER.OTHER;
}

/**
 * Translate a .gitignore glob into a RegExp over workspace-relative paths.
 *
 * A pragmatic subset, not a full gitignore implementation: `*`, `**`, `?`,
 * leading `/` anchoring, trailing `/` for directory-only, and `!` negation.
 * Character classes and the rarer corners are not supported. That covers every
 * pattern core/generator.js writes into a generated `.gitignore` plus the
 * ordinary hand-written ones; anything more exotic simply fails to match, which
 * costs a little scan time rather than producing a wrong index.
 */
function globToRegExp(glob, anchored) {
  let out = '';
  for (let i = 0; i < glob.length; i++) {
    const char = glob[i];
    if (char === '*') {
      if (glob[i + 1] === '*') { out += '.*'; i++; } else { out += '[^/]*'; }
    } else if (char === '?') {
      out += '[^/]';
    } else {
      out += char.replace(/[.+^${}()|[\]\\]/g, '\\$&');
    }
  }
  return new RegExp('^' + (anchored ? '' : '(?:.*/)?') + out + '(?:/.*)?$');
}

function parseIgnoreFile(root) {
  const file = path.join(root, '.gitignore');
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch (err) {
    return [];
  }
  return raw.split('\n').reduce(function (rules, line) {
    let pattern = line.trim();
    if (!pattern || pattern.indexOf('#') === 0) return rules;
    let negated = false;
    if (pattern.indexOf('!') === 0) { negated = true; pattern = pattern.slice(1); }
    let dirOnly = false;
    if (pattern.slice(-1) === '/') { dirOnly = true; pattern = pattern.slice(0, -1); }
    let anchored = false;
    if (pattern.indexOf('/') === 0) { anchored = true; pattern = pattern.slice(1); }
    if (pattern.indexOf('/') !== -1) anchored = true;
    if (!pattern) return rules;
    rules.push({ negated: negated, dirOnly: dirOnly, re: globToRegExp(pattern, anchored) });
    return rules;
  }, []);
}

/** Last matching rule wins, as git does, so a later `!` re-includes. */
function isIgnored(rules, relPath, isDir) {
  let ignored = false;
  rules.forEach(function (rule) {
    if (rule.dirOnly && !isDir) return;
    if (rule.re.test(relPath)) ignored = !rule.negated;
  });
  return ignored;
}

function walk(root, ignores, rules) {
  const found = [];
  (function recurse(dir) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (err) {
      return; // unreadable directory: report nothing rather than throw
    }
    entries.sort(function (a, b) { return a.name < b.name ? -1 : a.name > b.name ? 1 : 0; });
    entries.forEach(function (entry) {
      if (ignores.indexOf(entry.name) !== -1) return;
      const abs = path.join(dir, entry.name);
      const rel = toPosix(path.relative(root, abs));
      if (entry.isDirectory()) {
        if (isIgnored(rules, rel, true)) return;
        // A directory carrying its own .git is a separate repository -- a
        // submodule, a vendored checkout, or one of this tool's own worktrees.
        // Counting its files would fold a whole other project's size into this
        // workspace's metrics, which is exactly the kind of meaningless number
        // the health check (#78) must not be fed.
        if (fs.existsSync(path.join(abs, '.git'))) return;
        recurse(abs);
      } else if (entry.isFile()) {
        if (isIgnored(rules, rel, false)) return;
        found.push(abs);
      }
      // symlinks are deliberately not followed: a workspace is a tree, and
      // following links risks escaping the root or looping.
    });
  })(root);
  return found;
}

function readFileEntry(absPath, relPath, anchors, estimate) {
  const stat = fs.statSync(absPath);
  const buffer = fs.readFileSync(absPath);
  const binary = buffer.indexOf(0) !== -1;
  const entry = {
    path: relPath,
    layer: classify(relPath, anchors),
    bytes: stat.size,
    binary: binary,
  };
  if (binary) {
    // Counting lines or parsing markdown in a binary file would produce
    // meaningless numbers, so those fields are omitted rather than faked.
    entry.lines = null;
    entry.chars = null;
    entry.tokensEstimate = null;
    return { entry: entry, text: null };
  }
  const text = buffer.toString('utf8');
  entry.lines = countLines(text);
  entry.chars = text.length;
  entry.tokensEstimate = estimate(text);
  return { entry: entry, text: text };
}

/**
 * Split an agent-layer file into individually addressable instruction units,
 * one per markdown heading section (plus a preamble unit for any content before
 * the first heading -- generated CLAUDE.md files open with a bare `@AGENTS.md`
 * import, which is itself an instruction).
 *
 * Heading-section granularity is the spec's stated working default. The
 * Markdown Orchestrator is expected to settle the definitive unit; when it
 * does, this is the one place that changes.
 *
 * IDs are derived from the heading text, so they are stable across runs on an
 * unchanged file and survive content edits inside a section.
 */
function parseInstructions(relPath, text, estimate) {
  const lines = text.split('\n');
  const units = [];
  const usedIds = Object.create(null);
  let current = null;

  function makeId(label) {
    const base = relPath + '#' + slugify(label);
    if (!(base in usedIds)) {
      usedIds[base] = 1;
      return base;
    }
    usedIds[base] += 1;
    return base + '-' + usedIds[base];
  }

  function close(endLine) {
    if (!current) return;
    const body = lines.slice(current.startLine - 1, endLine).join('\n');
    current.endLine = endLine;
    current.chars = body.length;
    current.tokensEstimate = estimate(body);
    units.push(current);
    current = null;
  }

  let inFence = false;
  lines.forEach(function (line, index) {
    const lineNumber = index + 1;
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    const heading = inFence ? null : /^(#{1,6})\s+(.*\S)\s*$/.exec(line);
    if (heading) {
      close(lineNumber - 1);
      current = {
        id: makeId(heading[2]),
        file: relPath,
        heading: heading[2],
        level: heading[1].length,
        startLine: lineNumber,
        endLine: lineNumber,
        chars: 0,
        tokensEstimate: 0,
      };
    } else if (!current && line.trim() !== '') {
      current = {
        id: makeId('preamble'),
        file: relPath,
        heading: null,
        level: 0,
        startLine: lineNumber,
        endLine: lineNumber,
        chars: 0,
        tokensEstimate: 0,
      };
    }
  });
  close(lines.length);
  return units;
}

const VIA_PRECEDENCE = { import: 3, link: 2, mention: 1 };

/** Fenced code blocks are stripped before edge parsing: a path inside an
 * example command is documentation of a command, not a reference between
 * files, and counting it would fabricate edges. */
function stripFences(text) {
  const lines = text.split('\n');
  let inFence = false;
  return lines.map(function (line) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      return '';
    }
    return inFence ? '' : line;
  });
}

/** Character ranges covered by inline code spans on a single line. */
function codeSpans(line) {
  const spans = [];
  const re = /(`+)(?:(?!\1)[\s\S])*\1/g;
  let match;
  while ((match = re.exec(line)) !== null) {
    spans.push([match.index, match.index + match[0].length]);
  }
  return spans;
}

function inSpan(spans, index) {
  return spans.some(function (span) { return index >= span[0] && index < span[1]; });
}

function isExternal(target) {
  return /^[a-z][a-z0-9+.-]*:/i.test(target) || target.indexOf('//') === 0 || target.indexOf('#') === 0;
}

function resolveTarget(fromPath, target) {
  const clean = target.split('#')[0].split('?')[0].trim();
  if (!clean) return null;
  const dir = path.posix.dirname(fromPath);
  const joined = clean.indexOf('/') === 0
    ? clean.replace(/^\/+/, '')
    : path.posix.normalize(path.posix.join(dir === '.' ? '' : dir, clean));
  if (joined.indexOf('..') === 0) return null; // outside the workspace
  return joined;
}

/**
 * Cross-reference edges between workspace files -- the "RAG by Markdown" graph
 * named in CONTEXT.md. Three conventions are recognised:
 *
 *   import  `@AGENTS.md`                     (CLAUDE.md's generated import)
 *   link    `[text](docs/PRD.md)`            (standard markdown)
 *   mention  a bare or backticked filename   (prose references)
 *
 * At most one edge per file pair, keeping the strongest signal, so a file that
 * imports another and also mentions it in prose yields one edge, not two.
 * `resolved: false` marks a reference whose target is missing -- consumers
 * surface those as broken cross-references (#78, #169), so they must be
 * reported rather than dropped.
 */
function parseEdges(fromPath, text, knownPaths) {
  const lines = stripFences(text);
  const best = new Map();

  function record(to, via, line) {
    if (!to || to === fromPath) return;
    const existing = best.get(to);
    if (existing && VIA_PRECEDENCE[existing.via] >= VIA_PRECEDENCE[via]) return;
    best.set(to, {
      from: fromPath,
      to: to,
      via: via,
      line: line,
      resolved: knownPaths.has(to),
    });
  }

  lines.forEach(function (line, index) {
    const lineNumber = index + 1;
    const code = codeSpans(line);
    let match;

    const importRe = /(^|[\s(])@([A-Za-z0-9_./-]+\.[A-Za-z0-9]+)/g;
    while ((match = importRe.exec(line)) !== null) {
      if (inSpan(code, match.index)) continue;
      record(resolveTarget(fromPath, match[2]), 'import', lineNumber);
    }

    // Links inside inline code are syntax examples, not references. Writing
    // "standard `[text](path)` links" in a spec must not produce an edge to a
    // file called `path` -- the acceptance criterion for this graph is that it
    // fabricates none. Mentions below are exempt from this rule on purpose:
    // they only ever resolve against files that actually exist, and this repo's
    // prose refers to real files in backticks constantly.
    const linkRe = /\[[^\]]*\]\(([^)\s]+)[^)]*\)/g;
    while ((match = linkRe.exec(line)) !== null) {
      if (inSpan(code, match.index)) continue;
      if (isExternal(match[1])) continue;
      record(resolveTarget(fromPath, match[1]), 'link', lineNumber);
    }

    // Prose mentions: a known workspace path, optionally in backticks. Matching
    // against the actual file index rather than a filename pattern is what
    // keeps this from inventing edges to things that do not exist.
    const mentionRe = /`?([A-Za-z0-9_./-]+\.[A-Za-z0-9]+)`?/g;
    while ((match = mentionRe.exec(line)) !== null) {
      const candidate = match[1];
      if (knownPaths.has(candidate)) {
        record(candidate, 'mention', lineNumber);
      } else {
        const resolved = resolveTarget(fromPath, candidate);
        if (resolved && knownPaths.has(resolved)) record(resolved, 'mention', lineNumber);
      }
    }
  });

  return Array.from(best.values());
}

/**
 * Parse a `queue/*.md` stub into a structured item.
 *
 * The stub format is fixed by docs/specs/document-ingestion-queue.md (→ #80).
 * That spec, and docs/specs/cross-tool-session-log.md (→ #81) below, both
 * delegate *reading* their own files to this module -- "the kind of thing the
 * Workspace inspection layer exists to eventually provide" -- while #77's own
 * Non-Goals never claimed it. This is that gap closed: one reader here rather
 * than each consumer growing its own, which is the whole premise of #77.
 *
 * Status is normalised to `pending` / `ingested` while the raw string is kept,
 * so the grep convention (`grep -l "Status: Pending" queue/*.md`) and this
 * parser can never disagree about what an item's state is.
 */
function parseQueueItem(relPath, text) {
  function field(name) {
    const match = new RegExp('^\\s*[-*]\\s*\\*\\*' + name + ':\\*\\*\\s*(.+?)\\s*$', 'mi').exec(text);
    return match ? match[1].trim() : null;
  }
  const titleMatch = /^#\s+(?:Queue item\s+[—-]\s+)?(.+?)\s*$/m.exec(text);
  const rawStatus = field('Status');
  const ingestedOn = rawStatus ? (/\(([^)]+)\)/.exec(rawStatus) || [])[1] || null : null;
  const notesMatch = /^##\s+Notes\s*\n([\s\S]*)$/m.exec(text);
  return {
    path: relPath,
    title: titleMatch ? titleMatch[1].trim() : relPath,
    type: field('Type'),
    source: field('Source'),
    added: field('Added'),
    status: rawStatus && /^ingested/i.test(rawStatus) ? 'ingested' : 'pending',
    statusRaw: rawStatus,
    ingestedOn: ingestedOn,
    ingestedInto: field('Ingested into'),
    notes: notesMatch ? notesMatch[1].trim() : null,
  };
}

/**
 * Parse `SESSIONS.md` into its entries (docs/specs/cross-tool-session-log.md
 * → #81): one per `### <date> — <tool>` heading, with the Did / Left at fields
 * that spec fixes as the entry shape.
 *
 * Entries are returned newest-first, since every consumer of a handoff log
 * wants the most recent state first.
 */
function parseSessions(text) {
  const lines = text.split('\n');
  const entries = [];
  let current = null;

  function close(endLine) {
    if (!current) return;
    const body = lines.slice(current.startLine, endLine).join('\n');
    const did = /^\s*\*\*Did:\*\*\s*([\s\S]*?)(?=\n\s*\*\*|\n\s*$|$)/m.exec(body);
    const left = /^\s*\*\*Left at:\*\*\s*([\s\S]*?)(?=\n\s*\*\*|\n\s*$|$)/m.exec(body);
    current.did = did ? did[1].trim() : null;
    current.leftAt = left ? left[1].trim() : null;
    current.endLine = endLine;
    entries.push(current);
    current = null;
  }

  lines.forEach(function (line, index) {
    const heading = /^###\s+(\d{4}-\d{2}-\d{2})\s*[—-]\s*(.+?)\s*$/.exec(line);
    if (!heading) return;
    close(index);
    current = {
      date: heading[1],
      tool: heading[2].trim(),
      startLine: index + 1,
      endLine: index + 1,
      did: null,
      leftAt: null,
    };
  });
  close(lines.length);

  return entries.sort(function (a, b) {
    if (a.date !== b.date) return a.date < b.date ? 1 : -1;
    return b.startLine - a.startLine;
  });
}

/**
 * Is this folder a workspace//kit workspace?
 *
 * Scored rather than all-or-nothing, because the spec requires recognising a
 * workspace that has been hand-edited since generation, not only pristine
 * generator output. One point per signal file present (PROJECT/DECISIONS/
 * CONTEXT/TASKS) and one per agent-layer file; two points is the threshold.
 *
 * A single stray AGENTS.md or TASKS.md is therefore not enough, which is the
 * behaviour that matters -- consumers open arbitrary folders and a false
 * positive is worse than a false negative here.
 */
function detect(files) {
  const present = files.map(function (f) { return f.path; });
  const signals = SIGNAL_FILES.filter(function (name) { return present.indexOf(name) !== -1; });
  const agents = files
    .filter(function (f) { return f.layer === LAYER.AGENT; })
    .map(function (f) { return f.path; });
  const score = signals.length + agents.length;
  return {
    isWorkspace: score >= 2,
    score: score,
    signalFiles: signals,
    agentFiles: agents,
    reason: score >= 2
      ? 'Found ' + signals.length + ' human-layer anchor file(s) and ' + agents.length + ' agent-layer file(s).'
      : 'Not a workspace-kit workspace: found ' + score + ' recognised file(s), need at least 2 '
        + '(of PROJECT.md, DECISIONS.md, CONTEXT.md, TASKS.md, or any agent instruction file).',
  };
}

/**
 * Inspect a workspace folder.
 *
 * Read-only by construction: every filesystem call in this module is
 * readdirSync/statSync/readFileSync. Nothing here writes, moves or deletes.
 *
 * @param {string} rootDir           folder to inspect
 * @param {object} [options]
 * @param {string[]} [options.ignore]           extra directory/file names to skip
 * @param {boolean} [options.respectGitignore]  honour the workspace's own
 *        .gitignore (default true) -- without it a lived-in repo's metrics are
 *        dominated by build output and vendored content
 * @param {function} [options.estimateTokens]   override the token heuristic
 * @param {boolean} [options.includeText]       attach each instruction unit's text
 * @returns {object} the workspace index
 */
function inspect(rootDir, options) {
  const opts = options || {};
  const estimate = opts.estimateTokens || estimateTokens;
  const ignores = DEFAULT_IGNORES.concat(opts.ignore || []);
  const root = path.resolve(rootDir);

  if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
    return {
      root: root,
      isWorkspace: false,
      detection: {
        isWorkspace: false,
        score: 0,
        signalFiles: [],
        agentFiles: [],
        reason: 'Path does not exist or is not a directory.',
      },
      files: [],
      instructions: [],
      queue: [],
      sessions: [],
      graph: { nodes: [], edges: [] },
      totals: emptyTotals(),
    };
  }

  const anchors = anchorFilePaths();
  const rules = opts.respectGitignore === false ? [] : parseIgnoreFile(root);
  const absPaths = walk(root, ignores, rules);

  const files = [];
  const texts = new Map();
  absPaths.forEach(function (abs) {
    const rel = toPosix(path.relative(root, abs));
    const read = readFileEntry(abs, rel, anchors, estimate);
    files.push(read.entry);
    if (read.text !== null) texts.set(rel, read.text);
  });
  files.sort(function (a, b) { return a.path < b.path ? -1 : a.path > b.path ? 1 : 0; });

  const knownPaths = new Set(files.map(function (f) { return f.path; }));

  const instructions = [];
  files.forEach(function (file) {
    if (file.layer !== LAYER.AGENT || file.binary) return;
    parseInstructions(file.path, texts.get(file.path), estimate).forEach(function (unit) {
      if (opts.includeText) {
        const lines = texts.get(file.path).split('\n');
        unit.text = lines.slice(unit.startLine - 1, unit.endLine).join('\n');
      }
      instructions.push(unit);
    });
  });

  const edges = [];
  files.forEach(function (file) {
    if (file.binary || !/\.mdc?$/.test(file.path)) return;
    parseEdges(file.path, texts.get(file.path), knownPaths).forEach(function (edge) {
      edges.push(edge);
    });
  });
  edges.sort(function (a, b) {
    if (a.from !== b.from) return a.from < b.from ? -1 : 1;
    return a.to < b.to ? -1 : a.to > b.to ? 1 : 0;
  });

  const queue = files
    .filter(function (f) { return /^queue\/[^/]+\.md$/.test(f.path) && !f.binary; })
    .map(function (f) { return parseQueueItem(f.path, texts.get(f.path)); });

  const sessions = texts.has('SESSIONS.md') ? parseSessions(texts.get('SESSIONS.md')) : [];

  const detection = detect(files);

  return {
    root: root,
    isWorkspace: detection.isWorkspace,
    detection: detection,
    files: files,
    instructions: instructions,
    queue: queue,
    sessions: sessions,
    graph: {
      nodes: files.map(function (f) { return f.path; }),
      edges: edges,
    },
    totals: totalsFor(files),
  };
}

function emptyTotals() {
  return { files: 0, bytes: 0, lines: 0, chars: 0, tokensEstimate: 0, byLayer: {} };
}

function totalsFor(files) {
  const totals = emptyTotals();
  files.forEach(function (f) {
    totals.files += 1;
    totals.bytes += f.bytes;
    totals.lines += f.lines || 0;
    totals.chars += f.chars || 0;
    totals.tokensEstimate += f.tokensEstimate || 0;
    const layer = totals.byLayer[f.layer] || { files: 0, bytes: 0, tokensEstimate: 0 };
    layer.files += 1;
    layer.bytes += f.bytes;
    layer.tokensEstimate += f.tokensEstimate || 0;
    totals.byLayer[f.layer] = layer;
  });
  return totals;
}

/**
 * Debug entry point (spec P1): `node core/inspect.js [dir]` dumps the index as
 * JSON, so the module is inspectable by hand before the health check or the
 * dashboard exist to consume it. Not the `workspace-kit inspect` command --
 * that belongs to the CLI (#20) and should call `inspect()` directly.
 */
if (require.main === module) {
  const target = process.argv[2] || process.cwd();
  process.stdout.write(JSON.stringify(inspect(target), null, 2) + '\n');
}

module.exports = {
  inspect: inspect,
  estimateTokens: estimateTokens,
  countLines: countLines,
  parseInstructions: parseInstructions,
  parseEdges: parseEdges,
  parseQueueItem: parseQueueItem,
  parseSessions: parseSessions,
  anchorFilePaths: anchorFilePaths,
  HUMAN_FILES: HUMAN_FILES,
  SIGNAL_FILES: SIGNAL_FILES,
  AGENT_FILES: AGENT_FILES,
  AGENT_DIRS: AGENT_DIRS,
  LAYER: LAYER,
};
